// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESTAPI.Data;

namespace RESTAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210729190147_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RESTAPI.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentID = 2,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentID = 3,
                            DepartmentName = "PayRoll"
                        },
                        new
                        {
                            DepartmentID = 4,
                            DepartmentName = "Admin"
                        });
                });

            modelBuilder.Entity("RESTAPI.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentID = 1,
                            Email = "john@gmail.com",
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Peter"
                        },
                        new
                        {
                            ID = 2,
                            DepartmentID = 2,
                            Email = "john@gmail.com",
                            FirstName = "John1",
                            Gender = "Male",
                            LastName = "Peter"
                        },
                        new
                        {
                            ID = 3,
                            DepartmentID = 3,
                            Email = "john@gmail.com",
                            FirstName = "John2",
                            Gender = "Male",
                            LastName = "Peter"
                        },
                        new
                        {
                            ID = 4,
                            DepartmentID = 4,
                            Email = "john@gmail.com",
                            FirstName = "John3",
                            Gender = "Male",
                            LastName = "Peter"
                        });
                });

            modelBuilder.Entity("RESTAPI.Models.Employee", b =>
                {
                    b.HasOne("RESTAPI.Models.Department", "DepartmentName")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentName");
                });
#pragma warning restore 612, 618
        }
    }
}
